### PR TITLE
Do not read past the end of the input-stream

### PR DESCRIPTION
**Pull request by avodonosov**
When decoding underlying stream, chipz invokes read-sequence after the end of stream is reached. 
This can lead to endless wait in case of a synchronous network stream, or to an error, as in https://github.com/cl-plus-ssl/cl-plus-ssl/issues/166.

Note first, that `cl:read-sequence` signals EOF simply by reading smaller number of bytes than requested. The chipz library thinks this can be exercised several times. In this loop - https://github.com/sharplispers/chipz/blob/82a17d39c78d91f6ea63a03aca8f9aa6069a5e11/stream.lisp#L191 - it can refill its input buffer partially in one iteration, and then on next iteration try to refill the buffer again. The loop is exited only when `cl:read-sequence` for the underlying stream reads exactly zero bytes. That second attempt for `cl:read-sequence` causes the unexpected EOF.

This pull request fixes that problem both for `chipz:stream-reqd-sequence` and `chipz:read-and-decompress-byte`.

### CODE REVIEW

**Comment by stassats** [comment]
I would guess that setting input-eof-reached-p will make it harder to reuse the stream.

**Comment by avodonosov** [comment]
Reuse how?

**Comment by avodonosov** [comment]
Setting other input-stream is impossible, because the field is read only.

Or you mean the input-stream data has ended, and then new data is appeared (posted by the writer on the other side)?

**Comment by avodonosov** [comment]
@stassats, I've updated the pull request so that reading past EOF is only during invocation of a top level function, like cl:read-sequence or cl:read-byte. When user invokes such function next time, further reading is allowed (again, until EOF).

**Comment by stassats** [comment]
I think the EOF issue is just specific to chunked streams, on normal streams it's not a problem to read multiple times and get an EOF. And since I solved the issue on the drakma/chunga side, this pull request is not needed.

**Pull request closed without merging**
